// Copyright (c) 2026 LingByte. All rights reserved.
// SPDX-License-Identifier: AGPL-3.0

// Command schemadump runs GORM AutoMigrate against in-memory SQLite and prints
// a goose Up migration (CREATE TABLE/INDEX IF NOT EXISTS) to stdout.
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/LingByte/SoulNexus/cmd/bootstrap"
	"github.com/LingByte/SoulNexus/internal/config"
	pkgconst "github.com/LingByte/SoulNexus/pkg/constants"
	"github.com/LingByte/SoulNexus/pkg/logger"
	"github.com/glebarez/sqlite"
	"go.uber.org/zap"
	"gorm.io/gorm"
	gormlogger "gorm.io/gorm/logger"
)

func main() {
	config.GlobalConfig = &config.Config{
		Server:   config.ServerConfig{Mode: pkgconst.ENV_DEV, Addr: ":0", APIPrefix: "/api"},
		Database: config.DatabaseConfig{Driver: "sqlite", DSN: "file:schema_dump?mode=memory&cache=shared"},
	}
	// Avoid polluting stdout when redirecting to .sql (logger writes to stderr via zap by default;
	// still silence as much as possible).
	_ = logger.Init(&logger.LogConfig{Level: "panic", Filename: os.DevNull}, pkgconst.ENV_DEV)

	db, err := gorm.Open(sqlite.Open(config.GlobalConfig.Database.DSN), &gorm.Config{
		Logger: gormlogger.Default.LogMode(gormlogger.Silent),
	})
	if err != nil {
		fatal(err)
	}
	if err := bootstrap.RunMigrations(db); err != nil {
		fatal(err)
	}
	sqlDB, err := db.DB()
	if err != nil {
		fatal(err)
	}
	rows, err := sqlDB.Query(`
		SELECT sql FROM sqlite_master
		WHERE type IN ('table','index')
		  AND name NOT LIKE 'sqlite_%'
		  AND name NOT LIKE 'goose_%'
		  AND sql IS NOT NULL
		ORDER BY CASE type WHEN 'table' THEN 0 ELSE 1 END, name`)
	if err != nil {
		fatal(err)
	}
	defer rows.Close()

	fmt.Println("-- +goose Up")
	fmt.Println("-- AUTO-GENERATED by go run ./cmd/tools/schemadump")
	fmt.Println("-- Baseline schema from GORM models (SQLite). Idempotent CREATE IF NOT EXISTS.")
	fmt.Println("-- Do not edit by hand; re-run schemadump when models change, then add delta migrations.")
	fmt.Println()

	for rows.Next() {
		var sqlStmt string
		if err := rows.Scan(&sqlStmt); err != nil {
			fatal(err)
		}
		sqlStmt = strings.TrimSpace(sqlStmt)
		switch {
		case strings.HasPrefix(sqlStmt, "CREATE TABLE"):
			sqlStmt = "CREATE TABLE IF NOT EXISTS" + sqlStmt[len("CREATE TABLE"):]
		case strings.HasPrefix(sqlStmt, "CREATE UNIQUE INDEX"):
			sqlStmt = "CREATE UNIQUE INDEX IF NOT EXISTS" + sqlStmt[len("CREATE UNIQUE INDEX"):]
		case strings.HasPrefix(sqlStmt, "CREATE INDEX"):
			sqlStmt = "CREATE INDEX IF NOT EXISTS" + sqlStmt[len("CREATE INDEX"):]
		}
		fmt.Println(sqlStmt + ";")
		fmt.Println()
	}
	if err := rows.Err(); err != nil {
		fatal(err)
	}

	fmt.Println("-- +goose Down")
	fmt.Println("-- Intentionally empty: dropping the full product schema is destructive.")
}

func fatal(err error) {
	logger.Error("schemadump failed", zap.Error(err))
	fmt.Fprintf(os.Stderr, "schemadump: %v\n", err)
	os.Exit(1)
}
