// Copyright (c) 2026 LingByte. All rights reserved.
// SPDX-License-Identifier: AGPL-3.0

// Command genbodies scans Gin handlers for BindJSON request types and emits
// internal/handlers/openapi_bodies_gen.go so local + dto request structs both register.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type routeBind struct {
	Method string
	Path   string
	Type   string
}

func main() {
	root := "."
	if len(os.Args) > 1 {
		root = os.Args[1]
	}
	handlersDir := filepath.Join(root, "internal/handlers")
	outFile := filepath.Join(handlersDir, "openapi_bodies_gen.go")

	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, handlersDir, func(info os.FileInfo) bool {
		name := info.Name()
		return strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go") && name != "openapi_bodies_gen.go"
	}, 0)
	if err != nil {
		fatal(err)
	}

	handlerBodyType := map[string]string{}
	var files []*ast.File
	for _, pkg := range pkgs {
		for _, f := range pkg.Files {
			files = append(files, f)
		}
	}

	for _, f := range files {
		for _, d := range f.Decls {
			fn, ok := d.(*ast.FuncDecl)
			if !ok || fn.Body == nil || fn.Name == nil {
				continue
			}
			if t := findBindJSONType(fn); t != "" {
				handlerBodyType[fn.Name.Name] = t
			}
		}
	}

	var binds []routeBind
	for _, f := range files {
		binds = append(binds, scanRoutes(f, handlerBodyType)...)
	}

	seen := map[string]routeBind{}
	for _, b := range binds {
		if b.Type == "" || b.Path == "" {
			continue
		}
		seen[b.Method+" "+b.Path] = b
	}
	binds = binds[:0]
	for _, b := range seen {
		binds = append(binds, b)
	}
	sort.Slice(binds, func(i, j int) bool {
		if binds[i].Path == binds[j].Path {
			return binds[i].Method < binds[j].Method
		}
		return binds[i].Path < binds[j].Path
	})

	needDTO := false
	extImports := map[string]string{} // alias -> import path (from any file that uses it — approximate)
	for _, b := range binds {
		if strings.HasPrefix(b.Type, "dto.") || strings.HasPrefix(b.Type, "request.") {
			needDTO = true
		}
	}
	// Resolve external aliases from import specs across files
	aliasToPath := map[string]string{}
	for _, f := range files {
		for _, is := range f.Imports {
			path := strings.Trim(is.Path.Value, `"`)
			alias := ""
			if is.Name != nil {
				alias = is.Name.Name
			} else {
				// last path element
				parts := strings.Split(path, "/")
				alias = parts[len(parts)-1]
			}
			aliasToPath[alias] = path
		}
	}
	for _, b := range binds {
		if i := strings.IndexByte(b.Type, '.'); i > 0 {
			alias := b.Type[:i]
			if alias == "dto" || alias == "request" {
				continue
			}
			if p, ok := aliasToPath[alias]; ok {
				extImports[alias] = p
			}
		}
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by go run ./cmd/tools/genbodies; DO NOT EDIT.\n\n")
	buf.WriteString("package handlers\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"github.com/LingByte/SoulNexus/pkg/humax\"\n")
	if needDTO {
		buf.WriteString("\tdto \"github.com/LingByte/SoulNexus/internal/request\"\n")
	}
	aliases := make([]string, 0, len(extImports))
	for a := range extImports {
		aliases = append(aliases, a)
	}
	sort.Strings(aliases)
	for _, a := range aliases {
		fmt.Fprintf(&buf, "\t%s %q\n", a, extImports[a])
	}
	buf.WriteString(")\n\n")
	buf.WriteString("// RegisterOpenAPIBodies registers BindJSON request structs for OpenAPI Try-It.\n")
	buf.WriteString("func RegisterOpenAPIBodies() {\n")

	for _, b := range binds {
		typ := b.Type
		switch {
		case strings.HasPrefix(typ, "dto."):
			fmt.Fprintf(&buf, "\thumax.RegisterJSONBody(%q, %q, %s{})\n", b.Method, b.Path, typ)
		case strings.HasPrefix(typ, "request."):
			fmt.Fprintf(&buf, "\thumax.RegisterJSONBody(%q, %q, dto.%s{})\n", b.Method, b.Path, strings.TrimPrefix(typ, "request."))
		default:
			// local type or imported alias.type
			if i := strings.IndexByte(typ, '.'); i > 0 {
				alias := typ[:i]
				if _, ok := extImports[alias]; !ok && alias != "dto" {
					continue // unknown import — skip
				}
			}
			fmt.Fprintf(&buf, "\thumax.RegisterJSONBody(%q, %q, %s{})\n", b.Method, b.Path, typ)
		}
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "format error: %v\n%s\n", err, buf.String())
		os.Exit(1)
	}
	if err := os.WriteFile(outFile, formatted, 0o644); err != nil {
		fatal(err)
	}
	fmt.Printf("wrote %s (%d bodies)\n", outFile, len(binds))
}

func findBindJSONType(fn *ast.FuncDecl) string {
	var typ string
	ast.Inspect(fn.Body, func(n ast.Node) bool {
		if vs, ok := n.(*ast.ValueSpec); ok {
			for _, name := range vs.Names {
				if name.Name == "req" && vs.Type != nil {
					typ = exprString(vs.Type)
				}
			}
		}
		return true
	})
	if typ == "" {
		return ""
	}
	uses := false
	ast.Inspect(fn.Body, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		sel, ok := call.Fun.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		if sel.Sel.Name != "ShouldBindJSON" && sel.Sel.Name != "BindJSON" {
			return true
		}
		for _, a := range call.Args {
			if u, ok := a.(*ast.UnaryExpr); ok {
				if id, ok := u.X.(*ast.Ident); ok && id.Name == "req" {
					uses = true
				}
			}
		}
		return true
	})
	if !uses {
		return ""
	}
	return typ
}

func scanRoutes(f *ast.File, handlerBodyType map[string]string) []routeBind {
	var out []routeBind
	ast.Inspect(f, func(n ast.Node) bool {
		fn, ok := n.(*ast.FuncDecl)
		if !ok || fn.Body == nil {
			return true
		}
		if !strings.HasPrefix(fn.Name.Name, "register") && !strings.HasPrefix(fn.Name.Name, "Register") {
			return true
		}
		out = append(out, walkRegister(fn, handlerBodyType)...)
		return true
	})
	return out
}

func walkRegister(fn *ast.FuncDecl, handlerBodyType map[string]string) []routeBind {
	prefixes := map[string]string{
		"r": "/api", "protected": "/api", "admin": "/api", "g": "/api", "cr": "/api",
		"mine": "/api", "tenant": "/api", "notifChannels": "/api",
	}
	var binds []routeBind

	ast.Inspect(fn.Body, func(n ast.Node) bool {
		switch as := n.(type) {
		case *ast.AssignStmt:
			if len(as.Lhs) != 1 || len(as.Rhs) != 1 {
				return true
			}
			lhs, ok := as.Lhs[0].(*ast.Ident)
			if !ok {
				return true
			}
			call, ok := as.Rhs[0].(*ast.CallExpr)
			if !ok {
				return true
			}
			sel, ok := call.Fun.(*ast.SelectorExpr)
			if !ok || sel.Sel.Name != "Group" {
				return true
			}
			parent := recvName(sel.X)
			parentPrefix := prefixes[parent]
			if parentPrefix == "" {
				parentPrefix = "/api"
			}
			seg := ""
			if len(call.Args) > 0 {
				if lit, ok := call.Args[0].(*ast.BasicLit); ok {
					seg = strings.Trim(lit.Value, `"`)
				}
			}
			prefixes[lhs.Name] = join(parentPrefix, seg)
		case *ast.ExprStmt:
			call, ok := as.X.(*ast.CallExpr)
			if !ok {
				return true
			}
			sel, ok := call.Fun.(*ast.SelectorExpr)
			if !ok {
				return true
			}
			method := ""
			switch sel.Sel.Name {
			case "POST":
				method = "POST"
			case "PUT":
				method = "PUT"
			case "PATCH":
				method = "PATCH"
			default:
				return true
			}
			if len(call.Args) < 2 {
				return true
			}
			rel := ""
			if lit, ok := call.Args[0].(*ast.BasicLit); ok {
				rel = strings.Trim(lit.Value, `"`)
			}
			parent := recvName(sel.X)
			base := prefixes[parent]
			if base == "" {
				base = "/api"
			}
			full := toOpenAPIPath(join(base, strings.TrimPrefix(rel, "/")))
			hName := handlerName(call.Args[len(call.Args)-1])
			if hName == "" {
				return true
			}
			typ := handlerBodyType[hName]
			if typ == "" {
				return true
			}
			binds = append(binds, routeBind{Method: method, Path: full, Type: typ})
		}
		return true
	})
	return binds
}

func recvName(e ast.Expr) string {
	if id, ok := e.(*ast.Ident); ok {
		return id.Name
	}
	return ""
}

func handlerName(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.SelectorExpr:
		return t.Sel.Name
	case *ast.Ident:
		return t.Name
	default:
		return ""
	}
}

func exprString(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return exprString(t.X) + "." + t.Sel.Name
	case *ast.StarExpr:
		return exprString(t.X)
	default:
		return ""
	}
}

func join(base, rel string) string {
	base = strings.TrimSuffix(base, "/")
	rel = strings.Trim(rel, "/")
	if rel == "" {
		return base
	}
	return base + "/" + rel
}

func toOpenAPIPath(p string) string {
	parts := strings.Split(p, "/")
	for i, part := range parts {
		if strings.HasPrefix(part, ":") && len(part) > 1 {
			parts[i] = "{" + part[1:] + "}"
		}
	}
	return strings.Join(parts, "/")
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
