package backup

import (
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"
	"time"

	"github.com/LingByte/SoulNexus/pkg/config"
	"github.com/LingByte/SoulNexus/pkg/logger"
	"github.com/robfig/cron/v3"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// StartBackupScheduler starts the backup scheduler and executes backup immediately on startup
func StartBackupScheduler(db *gorm.DB) {
	// Execute backup immediately on startup
	logger.Info("Executing initial backup on startup...")
	c := cron.New()
	// Use Cron expression from configuration
	schedule := config.GlobalConfig.Features.BackupSchedule

	// Add scheduled task
	c.AddFunc(schedule, func() {
		err := ExecuteBackup(db)
		if err != nil {
			logger.Warn("Backup failed: %v", zap.Error(err))
		} else {
			logger.Info("Backup completed successfully")
		}
	})

	// Start the scheduler
	c.Start()
}

// ExecuteBackup executes database backup according to configuration
func ExecuteBackup(db *gorm.DB) error {
	switch config.GlobalConfig.Database.Driver {
	case "sqlite":
		// Execute SQLite backup
		dst := filepath.Join(config.GlobalConfig.Features.BackupPath, fmt.Sprintf("sys_backup_%s.db", time.Now().Format("20060102_150405")))
		return BackupSQLiteDatabase(config.GlobalConfig.Database.DSN, dst)
	case "mysql":
		// Use Go driver for MySQL backup
		dst := filepath.Join(config.GlobalConfig.Features.BackupPath, fmt.Sprintf("sys_backup_%s.sql", time.Now().Format("20060102_150405")))
		return BackupMySQLDatabaseWithDriver(db, dst)
	default:
		return fmt.Errorf("unsupported DB_DRIVER: %s", config.GlobalConfig.Database.Driver)
	}
}

// BackupSQLiteDatabase performs backup of SQLite database
func BackupSQLiteDatabase(src string, dst string) error {
	// Ensure destination path exists
	backupDir := filepath.Dir(dst)
	if _, err := os.Stat(backupDir); os.IsNotExist(err) {
		err := os.MkdirAll(backupDir, os.ModePerm)
		if err != nil {
			return fmt.Errorf("failed to create backup directory: %v", err)
		}
	}

	// Open source file
	sourceFile, err := os.Open(src)
	if err != nil {
		return fmt.Errorf("error opening source file: %v", err)
	}
	defer sourceFile.Close()

	// Create destination file
	destFile, err := os.Create(dst)
	if err != nil {
		return fmt.Errorf("error creating destination file: %v", err)
	}
	defer destFile.Close()

	// Copy data
	_, err = io.Copy(destFile, sourceFile)
	if err != nil {
		return fmt.Errorf("error copying data: %v", err)
	}

	log.Printf("SQLite database backup completed: %s", dst)
	return nil
}

// Helper function to find index of substring
func findIndex(s, substr string) int {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return i
		}
	}
	return -1
}

// BackupMySQLDatabaseWithDriver performs MySQL backup using Go driver (fallback method)
func BackupMySQLDatabaseWithDriver(db *gorm.DB, dst string) error {
	// Ensure destination path exists
	backupDir := filepath.Dir(dst)
	if _, err := os.Stat(backupDir); os.IsNotExist(err) {
		err := os.MkdirAll(backupDir, os.ModePerm)
		if err != nil {
			return fmt.Errorf("failed to create backup directory: %v", err)
		}
	}

	// Get raw SQL database connection
	sqlDB, err := db.DB()
	if err != nil {
		return fmt.Errorf("failed to get database connection: %v", err)
	}

	// Create backup file
	outFile, err := os.Create(dst)
	if err != nil {
		return fmt.Errorf("error creating backup file: %v", err)
	}
	defer outFile.Close()

	// Write SQL dump header
	header := `-- MySQL dump 10.13
-- Host: localhost
-- Generated by SoulNexus Backup System
-- Date: ` + time.Now().Format("2006-01-02 15:04:05") + `

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

`
	outFile.WriteString(header)

	// Get all table names
	var tables []string
	rows, err := sqlDB.Query("SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE()")
	if err != nil {
		return fmt.Errorf("failed to get table list: %v", err)
	}
	defer rows.Close()

	for rows.Next() {
		var tableName string
		if err := rows.Scan(&tableName); err != nil {
			return fmt.Errorf("failed to scan table name: %v", err)
		}
		tables = append(tables, tableName)
	}

	// Dump each table
	for _, table := range tables {
		// Get CREATE TABLE statement
		var createStmt string
		err := sqlDB.QueryRow(fmt.Sprintf("SHOW CREATE TABLE `%s`", table)).Scan(&table, &createStmt)
		if err != nil {
			logger.Warn("Failed to get CREATE TABLE for %s: %v", zap.String("table", table), zap.Error(err))
			continue
		}

		outFile.WriteString("\n-- Table structure for table `" + table + "`\n")
		outFile.WriteString("DROP TABLE IF EXISTS `" + table + "`;\n")
		outFile.WriteString(createStmt + ";\n")

		// Get table data
		dataRows, err := sqlDB.Query(fmt.Sprintf("SELECT * FROM `%s`", table))
		if err != nil {
			logger.Warn("Failed to query data from %s: %v", zap.String("table", table), zap.Error(err))
			continue
		}
		defer dataRows.Close()

		columns, err := dataRows.Columns()
		if err != nil {
			logger.Warn("Failed to get columns from %s: %v", zap.String("table", table), zap.Error(err))
			continue
		}

		outFile.WriteString("\n-- Dumping data for table `" + table + "`\n")

		for dataRows.Next() {
			values := make([]interface{}, len(columns))
			valuePtrs := make([]interface{}, len(columns))
			for i := range columns {
				valuePtrs[i] = &values[i]
			}

			if err := dataRows.Scan(valuePtrs...); err != nil {
				logger.Warn("Failed to scan row from %s: %v", zap.String("table", table), zap.Error(err))
				continue
			}

			// Build INSERT statement
			insertStmt := fmt.Sprintf("INSERT INTO `%s` VALUES (", table)
			for i, val := range values {
				if i > 0 {
					insertStmt += ","
				}
				if val == nil {
					insertStmt += "NULL"
				} else {
					insertStmt += fmt.Sprintf("'%v'", val)
				}
			}
			insertStmt += ");\n"
			outFile.WriteString(insertStmt)
		}
	}

	// Write footer
	footer := `
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
`
	outFile.WriteString(footer)

	log.Printf("MySQL database backup completed (using Go driver): %s", dst)
	return nil
}
