package backup

// Copyright (c) 2026 LingByte. All rights reserved.
// SPDX-License-Identifier: AGPL-3.0

import (
	"bytes"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/LingByte/SoulNexus/pkg/logger"
	"github.com/LingByte/SoulNexus/pkg/stores"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// backupPostgresToStore 备份 PostgreSQL 数据库到对象存储（导出 SQL 文本）
func backupPostgresToStore(db *gorm.DB, store stores.Store) error {
	if db == nil {
		return fmt.Errorf("get underlying sql.DB: gorm DB is nil")
	}
	sqlDB, err := db.DB()
	if err != nil {
		return fmt.Errorf("get underlying sql.DB: %w", err)
	}

	var buf bytes.Buffer

	buf.WriteString(fmt.Sprintf(`-- PostgreSQL dump
-- Generated by SoulNexus Backup System
-- Date: %s

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

`, time.Now().Format("2006-01-02 15:04:05")))

	// 获取所有用户表（排除系统 schema）
	rows, err := sqlDB.Query(`
		SELECT table_schema, table_name
		FROM information_schema.tables
		WHERE table_schema NOT IN ('pg_catalog', 'information_schema')
		AND table_type = 'BASE TABLE'
		ORDER BY table_schema, table_name
	`)
	if err != nil {
		return fmt.Errorf("query table list: %w", err)
	}
	defer rows.Close()

	type pgTable struct {
		schema string
		name   string
	}
	var tables []pgTable
	for rows.Next() {
		var t pgTable
		if err := rows.Scan(&t.schema, &t.name); err != nil {
			return fmt.Errorf("scan table name: %w", err)
		}
		tables = append(tables, t)
	}

	// 逐表导出
	for _, table := range tables {
		fullName := fmt.Sprintf(`"%s"."%s"`, table.schema, table.name)

		// ---- CREATE TABLE ----
		createSQL, err := buildPostgresCreateTable(sqlDB, table.schema, table.name)
		if err != nil {
			logger.Warn("Failed to build CREATE TABLE",
				zap.String("table", fullName), zap.Error(err))
			continue
		}
		buf.WriteString("\n-- Table structure for " + fullName + "\n")
		buf.WriteString("DROP TABLE IF EXISTS " + fullName + ";\n")
		buf.WriteString(createSQL + ";\n")

		// ---- Data dump ----
		dataRows, err := sqlDB.Query(fmt.Sprintf("SELECT * FROM %s", fullName))
		if err != nil {
			logger.Warn("Failed to query data",
				zap.String("table", fullName), zap.Error(err))
			continue
		}

		columns, err := dataRows.Columns()
		if err != nil {
			dataRows.Close()
			logger.Warn("Failed to get columns",
				zap.String("table", fullName), zap.Error(err))
			continue
		}

		buf.WriteString("\n-- Dumping data for " + fullName + "\n")

		values := make([]any, len(columns))
		valuePtrs := make([]any, len(columns))
		for i := range columns {
			valuePtrs[i] = &values[i]
		}

		colList := make([]string, len(columns))
		for i, c := range columns {
			colList[i] = fmt.Sprintf(`"%s"`, c)
		}
		colStr := strings.Join(colList, ", ")

		for dataRows.Next() {
			if err := dataRows.Scan(valuePtrs...); err != nil {
				logger.Warn("Failed to scan row",
					zap.String("table", fullName), zap.Error(err))
				continue
			}
			buf.WriteString(fmt.Sprintf("INSERT INTO %s (%s) VALUES (", fullName, colStr))
			for i, val := range values {
				if i > 0 {
					buf.WriteByte(',')
				}
				if val == nil {
					buf.WriteString("NULL")
				} else {
					// PostgreSQL 使用单引号转义
					s := fmt.Sprintf("%v", val)
					s = strings.ReplaceAll(s, "'", "''")
					fmt.Fprintf(&buf, "'%s'", s)
				}
			}
			buf.WriteString(");\n")
		}
		dataRows.Close()
	}

	key := backupKey("sql")
	data := buf.Bytes()
	if err := store.Write(key, bytes.NewReader(data)); err != nil {
		return fmt.Errorf("upload postgres backup to store: %w", err)
	}

	return recordBackupManifest(key, int64(len(data)), store)
}

// buildPostgresCreateTable 从 information_schema 重建 CREATE TABLE 语句
func buildPostgresCreateTable(sqlDB *sql.DB, schema, table string) (string, error) {
	// 获取列定义
	colRows, err := sqlDB.Query(
		`SELECT column_name, data_type,
			CASE WHEN character_maximum_length IS NOT NULL
				THEN '(' || character_maximum_length || ')'
				ELSE ''
			END AS data_len,
			is_nullable,
			COALESCE(column_default, '') AS column_default
		FROM information_schema.columns
		WHERE table_schema = $1 AND table_name = $2
		ORDER BY ordinal_position`,
		schema, table,
	)
	if err != nil {
		return "", fmt.Errorf("query columns: %w", err)
	}
	defer colRows.Close()

	var cols []string
	for colRows.Next() {
		var name, dataType, dataLen, nullable, defaultVal string
		if err := colRows.Scan(&name, &dataType, &dataLen, &nullable, &defaultVal); err != nil {
			return "", fmt.Errorf("scan column: %w", err)
		}
		col := fmt.Sprintf(`    "%s" %s%s`, name, dataType, dataLen)
		if nullable == "NO" {
			col += " NOT NULL"
		}
		if defaultVal != "" {
			col += " DEFAULT " + defaultVal
		}
		cols = append(cols, col)
	}

	// 获取主键
	pkRows, err := sqlDB.Query(
		`SELECT kcu.column_name
		FROM information_schema.table_constraints tc
		JOIN information_schema.key_column_usage kcu
			ON tc.constraint_name = kcu.constraint_name
			AND tc.table_schema = kcu.table_schema
		WHERE tc.constraint_type = 'PRIMARY KEY'
			AND tc.table_schema = $1
			AND tc.table_name = $2
		ORDER BY kcu.ordinal_position`,
		schema, table,
	)
	if err != nil {
		return "", fmt.Errorf("query primary keys: %w", err)
	}
	defer pkRows.Close()

	var pkCols []string
	for pkRows.Next() {
		var col string
		if err := pkRows.Scan(&col); err != nil {
			return "", fmt.Errorf("scan pk: %w", err)
		}
		pkCols = append(pkCols, fmt.Sprintf(`"%s"`, col))
	}

	fullName := fmt.Sprintf(`"%s"."%s"`, schema, table)
	createSQL := fmt.Sprintf("CREATE TABLE %s (\n%s\n)", fullName, strings.Join(cols, ",\n"))
	if len(pkCols) > 0 {
		createSQL += fmt.Sprintf(";\nALTER TABLE %s ADD PRIMARY KEY (%s)", fullName, strings.Join(pkCols, ", "))
	}

	return createSQL, nil
}
