package backup

// Copyright (c) 2026 LingByte. All rights reserved.
// SPDX-License-Identifier: AGPL-3.0

import (
	"bytes"
	"fmt"
	"time"

	"github.com/LingByte/SoulNexus/pkg/logger"
	"github.com/LingByte/SoulNexus/pkg/stores"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// backupMySQLToStore 备份 MySQL 数据库到对象存储（导出 SQL 文本）
func backupMySQLToStore(db *gorm.DB, store stores.Store) error {
	sqlDB, err := db.DB()
	if err != nil {
		return fmt.Errorf("get underlying sql.DB: %w", err)
	}

	var buf bytes.Buffer

	header := fmt.Sprintf(`-- MySQL dump
-- Generated by SoulNexus Backup System
-- Date: %s

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

`, time.Now().Format("2006-01-02 15:04:05"))
	buf.WriteString(header)

	// 获取所有表名
	rows, err := sqlDB.Query("SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE()")
	if err != nil {
		return fmt.Errorf("query table list: %w", err)
	}
	defer rows.Close()

	var tables []string
	for rows.Next() {
		var tableName string
		if err := rows.Scan(&tableName); err != nil {
			return fmt.Errorf("scan table name: %w", err)
		}
		tables = append(tables, tableName)
	}

	// 逐表导出
	for _, table := range tables {
		var createStmt string
		q := fmt.Sprintf("SHOW CREATE TABLE `%s`", table)
		if err := sqlDB.QueryRow(q).Scan(&table, &createStmt); err != nil {
			logger.Warn("Failed to get CREATE TABLE", zap.String("table", table), zap.Error(err))
			continue
		}
		buf.WriteString("\n-- Table structure for `" + table + "`\n")
		buf.WriteString("DROP TABLE IF EXISTS `" + table + "`;\n")
		buf.WriteString(createStmt + ";\n")

		dataRows, err := sqlDB.Query(fmt.Sprintf("SELECT * FROM `%s`", table))
		if err != nil {
			logger.Warn("Failed to query data", zap.String("table", table), zap.Error(err))
			continue
		}

		columns, err := dataRows.Columns()
		if err != nil {
			dataRows.Close()
			logger.Warn("Failed to get columns", zap.String("table", table), zap.Error(err))
			continue
		}

		buf.WriteString("\n-- Dumping data for `" + table + "`\n")

		values := make([]any, len(columns))
		valuePtrs := make([]any, len(columns))
		for i := range columns {
			valuePtrs[i] = &values[i]
		}

		for dataRows.Next() {
			if err := dataRows.Scan(valuePtrs...); err != nil {
				logger.Warn("Failed to scan row", zap.String("table", table), zap.Error(err))
				continue
			}
			buf.WriteString(fmt.Sprintf("INSERT INTO `%s` VALUES (", table))
			for i, val := range values {
				if i > 0 {
					buf.WriteByte(',')
				}
				if val == nil {
					buf.WriteString("NULL")
				} else {
					fmt.Fprintf(&buf, "'%v'", val)
				}
			}
			buf.WriteString(");\n")
		}
		dataRows.Close()
	}

	footer := `
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
`
	buf.WriteString(footer)

	key := backupKey("sql")
	data := buf.Bytes()
	if err := store.Write(key, bytes.NewReader(data)); err != nil {
		return fmt.Errorf("upload mysql backup to store: %w", err)
	}

	return recordBackupManifest(key, int64(len(data)), store)
}
