// Code generated by go run ./cmd/tools/genbodies; DO NOT EDIT.

package humax

// RegisterGeneratedBodies kept for compatibility; prefer handlers.RegisterOpenAPIBodies.
func RegisterGeneratedBodies() {}
