package handlers

import (
	"net/http"
	"strconv"
	"strings"

	"github.com/LingByte/SoulNexus/internal/models"
	"github.com/LingByte/SoulNexus/pkg/middleware"
	"github.com/LingByte/SoulNexus/pkg/utils/timeutil"
	"github.com/LingByte/SoulNexus/pkg/utils/ginutil"
	"github.com/gin-gonic/gin"
)

// listMyOperationLogs returns audit rows generated by the currently authenticated
// user within their tenant (no tenantId exposed; actions only reflect this user).
//
//	Endpoint: GET /operation-logs/me (tenant-scoped).
//
// Path parameters: none.
//
// Query parameters (see buildOperationLogQueryFilter for full list):
//
//	page      (int, default 1)  - pagination page number.
//	size      (int, default 100) - page size.
//	action    (string)          - filter by action verb (e.g. "create", "delete").
//	resource  (string)          - filter by resource kind (e.g. "tenant_user").
//	resourceId (uint)            - filter by specific resource id.
//	success   (bool string)     - "1"/"true"/"yes" or "0"/"false"/"no".
//	from      (time)            - start time (RFC3339 / "2006-01-02 15:04:05" / date only).
//	to        (time)            - end time (same formats as from).
//
// Request body: none.
//
// Response (paginated):
//
//	{
//	  "code": 200, "msg": "success",
//	  "data": [ ...OperationLogMineView... ],
//	  "total": int, "page": int, "size": int
//	}
func (h *Handlers) listMyOperationLogs(c *gin.Context) {
	email := middleware.AuthEmail(c)
	tid := middleware.CurrentTenantID(c)
	if email == "" || tid == 0 {
		c.AbortWithStatusJSON(http.StatusForbidden, gin.H{"code": 403, "msg": "forbidden", "data": nil})
		return
	}
	page, size := ginutil.QueryPage(c, 100)
	filter := buildOperationLogQueryFilter(c)
	filter.TenantID = tid
	filter.OperatorExact = email

	list, total, err := models.ListOperationLogsPage(h.db, page, size, filter)
	if ginutil.WriteInternalError(c, err) {
		return
	}
	views := make([]models.OperationLogMineView, 0, len(list))
	for _, row := range list {
		views = append(views, models.ToOperationLogMineView(row))
	}
	ginutil.PageSuccess(c, views, total, page, size)
}

// listTenantOperationLogs returns all audit rows for the current tenant (includes
// AK/SK credential ops and any tenant-scoped write).
//
//	Endpoint: GET /operation-logs (tenant-scoped).
//
// Path parameters: none.
//
// Query parameters: same as listMyOperationLogs (page, size, action, resource,
// resourceId, success, from, to).
//
// Request body: none.
//
// Response (paginated):
//
//	{
//	  "code": 200, "msg": "success",
//	  "data": [ ...OperationLogMineView... ],
//	  "total": int, "page": int, "size": int
//	}
func (h *Handlers) listTenantOperationLogs(c *gin.Context) {
	tid := middleware.CurrentTenantID(c)
	if tid == 0 {
		if middleware.AuthPlatformAdminID(c) > 0 {
			c.AbortWithStatusJSON(http.StatusBadRequest, gin.H{"code": 400, "msg": "tenantId query required for platform admin", "data": nil})
			return
		}
		c.AbortWithStatusJSON(http.StatusForbidden, gin.H{"code": 403, "msg": "forbidden", "data": nil})
		return
	}
	page, size := ginutil.QueryPage(c, 100)
	filter := buildOperationLogQueryFilter(c)
	filter.TenantID = tid

	list, total, err := models.ListOperationLogsPage(h.db, page, size, filter)
	if ginutil.WriteInternalError(c, err) {
		return
	}
	views := make([]models.OperationLogMineView, 0, len(list))
	for _, row := range list {
		views = append(views, models.ToOperationLogMineView(row))
	}
	ginutil.PageSuccess(c, views, total, page, size)
}

// listOperationLogsPlatform returns all audit rows across all tenants for
// platform admins (tenantId is exposed in each row for filtering).
//
//	Endpoint: GET /platform/operation-logs (platform-admin scoped).
//
// Path parameters: none.
//
// Query parameters: same as listMyOperationLogs plus:
//
//	tenantId (uint) - restrict logs to a specific tenant.
//
// Request body: none.
//
// Response (paginated):
//
//	{
//	  "code": 200, "msg": "success",
//	  "data": [ ...OperationLog full row (includes tenantId)... ],
//	  "total": int, "page": int, "size": int
//	}
func (h *Handlers) listOperationLogsPlatform(c *gin.Context) {
	page, size := ginutil.QueryPage(c, 100)
	filter := buildOperationLogQueryFilter(c)
	if s := strings.TrimSpace(c.Query("tenantId")); s != "" {
		if v, err := strconv.ParseUint(s, 10, 64); err == nil {
			filter.TenantID = uint(v)
		}
	}
	list, total, err := models.ListOperationLogsPage(h.db, page, size, filter)
	if ginutil.WriteInternalError(c, err) {
		return
	}
	ginutil.PageSuccess(c, list, total, page, size)
}

func buildOperationLogQueryFilter(c *gin.Context) models.OperationLogListFilter {
	filter := models.OperationLogListFilter{
		Operator: strings.TrimSpace(c.Query("operator")),
		Action:   strings.TrimSpace(c.Query("action")),
		Resource: strings.TrimSpace(c.Query("resource")),
	}
	if s := strings.TrimSpace(c.Query("resourceId")); s != "" {
		if v, err := strconv.ParseUint(s, 10, 64); err == nil {
			filter.ResourceID = uint(v)
		}
	}
	if s := strings.TrimSpace(c.Query("success")); s != "" {
		switch strings.ToLower(s) {
		case "1", "true", "yes":
			t := true
			filter.Success = &t
		case "0", "false", "no":
			f := false
			filter.Success = &f
		}
	}
	if t, ok := timeutil.ParseQueryTime(c.Query("from")); ok {
		filter.From = &t
	}
	if t, ok := timeutil.ParseQueryTime(c.Query("to")); ok {
		filter.To = &t
	}
	return filter
}
