package constants

// GORM table names (shared by models and raw SQL joins).

const (
	TENANT_TABLE_NAME                        = "tenants"
	TENANT_GROUP_TABLE_NAME                  = "tenant_groups"
	TENANT_USER_TABLE_NAME                   = "tenant_users"
	TENANT_USER_GROUP_TABLE_NAME             = "tenant_user_groups"
	PERMISSION_TABLE_NAME                    = "permissions"
	TENANT_ROLE_TABLE_NAME                   = "tenant_roles"
	TENANT_ROLE_PERMISSION_TABLE_NAME        = "tenant_role_permissions"
	TENANT_USER_ROLE_TABLE_NAME              = "tenant_user_roles"
	CREDENTIAL_TABLE_NAME                    = "credential"
	PLATFORM_ADMIN_TABLE_NAME                = "platform_admins"
	OPERATION_LOG_TABLE_NAME                 = "operation_logs"
	KNOWLEDGE_NAMESPACE_TABLE_NAME           = "knowledge_namespaces"
	KNOWLEDGE_DOCUMENT_TABLE_NAME            = "knowledge_documents"
	KNOWLEDGE_CHUNK_TABLE_NAME               = "knowledge_chunks"
	KNOWLEDGE_UNANSWERED_QUESTION_TABLE_NAME = "knowledge_unanswered_questions"
	KNOWLEDGE_ANSWERED_QUESTION_TABLE_NAME   = "knowledge_answered_questions"
	KNOWLEDGE_TYPICAL_QUESTION_TABLE_NAME    = "knowledge_typical_questions"
	KNOWLEDGE_TYPICAL_QUESTION_STAT_TABLE    = "knowledge_typical_question_stats"
	KNOWLEDGE_SYNC_SOURCE_TABLE_NAME         = "knowledge_sync_sources"
	KNOWLEDGE_EVAL_DATASET_TABLE_NAME        = "knowledge_eval_datasets"
	AI_REPORT_TABLE_NAME                     = "ai_reports"
	TENANT_BILL_TABLE_NAME                   = "tenant_bills"
	TENANT_USAGE_EVENT_TABLE_NAME            = "tenant_usage_events"
	BILLING_PLAN_TABLE_NAME                  = "billing_plans"
	TENANT_WEBHOOK_TABLE_NAME                = "tenant_webhooks"
	TENANT_WEBHOOK_DELIVERY_TABLE_NAME       = "tenant_webhook_deliveries"
	TENANT_IM_CHANNEL_TABLE_NAME             = "tenant_im_channels"
	DIALOG_CONVERSATION_TABLE_NAME           = "dialog_conversations"
	DIALOG_MESSAGE_TABLE_NAME                = "dialog_messages"
	TENANT_DIALOG_CHANNEL_TABLE_NAME         = "tenant_dialog_channels"
	TENANT_DIALOG_SKILL_TABLE_NAME           = "tenant_dialog_skills"
	LOGIN_HISTORY_TABLE_NAME                 = "login_history"
	EXECUTION_TASK_TABLE_NAME                = "execution_tasks"
	ASSISTANT_TABLE_NAME                     = "assistants"
	ASSISTANT_VERSION_TABLE_NAME             = "assistant_versions"
	JS_TEMPLATE_TABLE_NAME                   = "js_templates"
	JS_TEMPLATE_USAGE_TABLE_NAME             = "js_template_usage_logs"
	VOICE_CLONE_PROFILE_TABLE_NAME           = "voice_clone_profiles"
	VOICEPRINT_PROFILE_TABLE_NAME            = "voiceprints"
	SPEAKER_SUBJECT_TABLE_NAME               = "speaker_subjects"
	SPEAKER_ATTRIBUTE_TABLE_NAME             = "speaker_attributes"
	SPEAKER_CREDENTIAL_TABLE_NAME            = "speaker_credentials"
	VOICE_SYNTHESIS_HISTORY_TABLE_NAME       = "voice_synthesis_histories"
	MAIL_LOGS_TABLE_NAME                     = "mail_logs"
	AI_INVOCATION_LOGS_TABLE_NAME            = "ai_invocation_logs"
	TENANT_NLU_MODEL_TABLE_NAME              = "tenant_nlu_models"
	TENANT_ASSISTANT_TOOL_TABLE_NAME         = "tenant_assistant_tools"
	MCP_MARKET_ITEM_TABLE_NAME               = "mcp_market_items"
)
