// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: auth/v1/auth.proto

package authv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserAuthService_GetUser_FullMethodName                     = "/auth.v1.UserAuthService/GetUser"
	UserAuthService_GetUserByEmail_FullMethodName              = "/auth.v1.UserAuthService/GetUserByEmail"
	UserAuthService_ResolveCredential_FullMethodName           = "/auth.v1.UserAuthService/ResolveCredential"
	UserAuthService_ListUserCredentials_FullMethodName         = "/auth.v1.UserAuthService/ListUserCredentials"
	UserAuthService_GetCredential_FullMethodName               = "/auth.v1.UserAuthService/GetCredential"
	UserAuthService_DeleteCredential_FullMethodName            = "/auth.v1.UserAuthService/DeleteCredential"
	UserAuthService_MarkCredentialUsed_FullMethodName          = "/auth.v1.UserAuthService/MarkCredentialUsed"
	UserAuthService_AdminListCredentials_FullMethodName        = "/auth.v1.UserAuthService/AdminListCredentials"
	UserAuthService_UpdateCredentialStatus_FullMethodName      = "/auth.v1.UserAuthService/UpdateCredentialStatus"
	UserAuthService_CreateUserCredential_FullMethodName        = "/auth.v1.UserAuthService/CreateUserCredential"
	UserAuthService_DeleteUserCredentialForUser_FullMethodName = "/auth.v1.UserAuthService/DeleteUserCredentialForUser"
)

// UserAuthServiceClient is the client API for UserAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UserAuthService is the internal RPC surface from cmd/server (and peers) to cmd/auth.
// Browser-facing auth stays on HTTP; JWT claims are validated locally on server.
// Anything that needs DB-backed user rows or API secrets must use this service.
type UserAuthServiceClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	GetUserByEmail(ctx context.Context, in *GetUserByEmailRequest, opts ...grpc.CallOption) (*User, error)
	ResolveCredential(ctx context.Context, in *ResolveCredentialRequest, opts ...grpc.CallOption) (*UserCredential, error)
	ListUserCredentials(ctx context.Context, in *ListUserCredentialsRequest, opts ...grpc.CallOption) (*ListUserCredentialsResponse, error)
	GetCredential(ctx context.Context, in *GetCredentialRequest, opts ...grpc.CallOption) (*UserCredential, error)
	DeleteCredential(ctx context.Context, in *DeleteCredentialRequest, opts ...grpc.CallOption) (*DeleteCredentialResponse, error)
	MarkCredentialUsed(ctx context.Context, in *MarkCredentialUsedRequest, opts ...grpc.CallOption) (*MarkCredentialUsedResponse, error)
	AdminListCredentials(ctx context.Context, in *AdminListCredentialsRequest, opts ...grpc.CallOption) (*AdminListCredentialsResponse, error)
	UpdateCredentialStatus(ctx context.Context, in *UpdateCredentialStatusRequest, opts ...grpc.CallOption) (*UserCredential, error)
	CreateUserCredential(ctx context.Context, in *CreateUserCredentialRequest, opts ...grpc.CallOption) (*UserCredential, error)
	DeleteUserCredentialForUser(ctx context.Context, in *DeleteUserCredentialForUserRequest, opts ...grpc.CallOption) (*DeleteCredentialResponse, error)
}

type userAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserAuthServiceClient(cc grpc.ClientConnInterface) UserAuthServiceClient {
	return &userAuthServiceClient{cc}
}

func (c *userAuthServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UserAuthService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthServiceClient) GetUserByEmail(ctx context.Context, in *GetUserByEmailRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UserAuthService_GetUserByEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthServiceClient) ResolveCredential(ctx context.Context, in *ResolveCredentialRequest, opts ...grpc.CallOption) (*UserCredential, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCredential)
	err := c.cc.Invoke(ctx, UserAuthService_ResolveCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthServiceClient) ListUserCredentials(ctx context.Context, in *ListUserCredentialsRequest, opts ...grpc.CallOption) (*ListUserCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserCredentialsResponse)
	err := c.cc.Invoke(ctx, UserAuthService_ListUserCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthServiceClient) GetCredential(ctx context.Context, in *GetCredentialRequest, opts ...grpc.CallOption) (*UserCredential, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCredential)
	err := c.cc.Invoke(ctx, UserAuthService_GetCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthServiceClient) DeleteCredential(ctx context.Context, in *DeleteCredentialRequest, opts ...grpc.CallOption) (*DeleteCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCredentialResponse)
	err := c.cc.Invoke(ctx, UserAuthService_DeleteCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthServiceClient) MarkCredentialUsed(ctx context.Context, in *MarkCredentialUsedRequest, opts ...grpc.CallOption) (*MarkCredentialUsedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkCredentialUsedResponse)
	err := c.cc.Invoke(ctx, UserAuthService_MarkCredentialUsed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthServiceClient) AdminListCredentials(ctx context.Context, in *AdminListCredentialsRequest, opts ...grpc.CallOption) (*AdminListCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListCredentialsResponse)
	err := c.cc.Invoke(ctx, UserAuthService_AdminListCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthServiceClient) UpdateCredentialStatus(ctx context.Context, in *UpdateCredentialStatusRequest, opts ...grpc.CallOption) (*UserCredential, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCredential)
	err := c.cc.Invoke(ctx, UserAuthService_UpdateCredentialStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthServiceClient) CreateUserCredential(ctx context.Context, in *CreateUserCredentialRequest, opts ...grpc.CallOption) (*UserCredential, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCredential)
	err := c.cc.Invoke(ctx, UserAuthService_CreateUserCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthServiceClient) DeleteUserCredentialForUser(ctx context.Context, in *DeleteUserCredentialForUserRequest, opts ...grpc.CallOption) (*DeleteCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCredentialResponse)
	err := c.cc.Invoke(ctx, UserAuthService_DeleteUserCredentialForUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserAuthServiceServer is the server API for UserAuthService service.
// All implementations must embed UnimplementedUserAuthServiceServer
// for forward compatibility.
//
// UserAuthService is the internal RPC surface from cmd/server (and peers) to cmd/auth.
// Browser-facing auth stays on HTTP; JWT claims are validated locally on server.
// Anything that needs DB-backed user rows or API secrets must use this service.
type UserAuthServiceServer interface {
	GetUser(context.Context, *GetUserRequest) (*User, error)
	GetUserByEmail(context.Context, *GetUserByEmailRequest) (*User, error)
	ResolveCredential(context.Context, *ResolveCredentialRequest) (*UserCredential, error)
	ListUserCredentials(context.Context, *ListUserCredentialsRequest) (*ListUserCredentialsResponse, error)
	GetCredential(context.Context, *GetCredentialRequest) (*UserCredential, error)
	DeleteCredential(context.Context, *DeleteCredentialRequest) (*DeleteCredentialResponse, error)
	MarkCredentialUsed(context.Context, *MarkCredentialUsedRequest) (*MarkCredentialUsedResponse, error)
	AdminListCredentials(context.Context, *AdminListCredentialsRequest) (*AdminListCredentialsResponse, error)
	UpdateCredentialStatus(context.Context, *UpdateCredentialStatusRequest) (*UserCredential, error)
	CreateUserCredential(context.Context, *CreateUserCredentialRequest) (*UserCredential, error)
	DeleteUserCredentialForUser(context.Context, *DeleteUserCredentialForUserRequest) (*DeleteCredentialResponse, error)
	mustEmbedUnimplementedUserAuthServiceServer()
}

// UnimplementedUserAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserAuthServiceServer struct{}

func (UnimplementedUserAuthServiceServer) GetUser(context.Context, *GetUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserAuthServiceServer) GetUserByEmail(context.Context, *GetUserByEmailRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByEmail not implemented")
}
func (UnimplementedUserAuthServiceServer) ResolveCredential(context.Context, *ResolveCredentialRequest) (*UserCredential, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveCredential not implemented")
}
func (UnimplementedUserAuthServiceServer) ListUserCredentials(context.Context, *ListUserCredentialsRequest) (*ListUserCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserCredentials not implemented")
}
func (UnimplementedUserAuthServiceServer) GetCredential(context.Context, *GetCredentialRequest) (*UserCredential, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCredential not implemented")
}
func (UnimplementedUserAuthServiceServer) DeleteCredential(context.Context, *DeleteCredentialRequest) (*DeleteCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCredential not implemented")
}
func (UnimplementedUserAuthServiceServer) MarkCredentialUsed(context.Context, *MarkCredentialUsedRequest) (*MarkCredentialUsedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkCredentialUsed not implemented")
}
func (UnimplementedUserAuthServiceServer) AdminListCredentials(context.Context, *AdminListCredentialsRequest) (*AdminListCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminListCredentials not implemented")
}
func (UnimplementedUserAuthServiceServer) UpdateCredentialStatus(context.Context, *UpdateCredentialStatusRequest) (*UserCredential, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCredentialStatus not implemented")
}
func (UnimplementedUserAuthServiceServer) CreateUserCredential(context.Context, *CreateUserCredentialRequest) (*UserCredential, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserCredential not implemented")
}
func (UnimplementedUserAuthServiceServer) DeleteUserCredentialForUser(context.Context, *DeleteUserCredentialForUserRequest) (*DeleteCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserCredentialForUser not implemented")
}
func (UnimplementedUserAuthServiceServer) mustEmbedUnimplementedUserAuthServiceServer() {}
func (UnimplementedUserAuthServiceServer) testEmbeddedByValue()                         {}

// UnsafeUserAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserAuthServiceServer will
// result in compilation errors.
type UnsafeUserAuthServiceServer interface {
	mustEmbedUnimplementedUserAuthServiceServer()
}

func RegisterUserAuthServiceServer(s grpc.ServiceRegistrar, srv UserAuthServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserAuthService_ServiceDesc, srv)
}

func _UserAuthService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuthService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAuthService_GetUserByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServiceServer).GetUserByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuthService_GetUserByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServiceServer).GetUserByEmail(ctx, req.(*GetUserByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAuthService_ResolveCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServiceServer).ResolveCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuthService_ResolveCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServiceServer).ResolveCredential(ctx, req.(*ResolveCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAuthService_ListUserCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServiceServer).ListUserCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuthService_ListUserCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServiceServer).ListUserCredentials(ctx, req.(*ListUserCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAuthService_GetCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServiceServer).GetCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuthService_GetCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServiceServer).GetCredential(ctx, req.(*GetCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAuthService_DeleteCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServiceServer).DeleteCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuthService_DeleteCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServiceServer).DeleteCredential(ctx, req.(*DeleteCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAuthService_MarkCredentialUsed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkCredentialUsedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServiceServer).MarkCredentialUsed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuthService_MarkCredentialUsed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServiceServer).MarkCredentialUsed(ctx, req.(*MarkCredentialUsedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAuthService_AdminListCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServiceServer).AdminListCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuthService_AdminListCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServiceServer).AdminListCredentials(ctx, req.(*AdminListCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAuthService_UpdateCredentialStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCredentialStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServiceServer).UpdateCredentialStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuthService_UpdateCredentialStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServiceServer).UpdateCredentialStatus(ctx, req.(*UpdateCredentialStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAuthService_CreateUserCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServiceServer).CreateUserCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuthService_CreateUserCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServiceServer).CreateUserCredential(ctx, req.(*CreateUserCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAuthService_DeleteUserCredentialForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserCredentialForUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthServiceServer).DeleteUserCredentialForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAuthService_DeleteUserCredentialForUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthServiceServer).DeleteUserCredentialForUser(ctx, req.(*DeleteUserCredentialForUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserAuthService_ServiceDesc is the grpc.ServiceDesc for UserAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.UserAuthService",
	HandlerType: (*UserAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserAuthService_GetUser_Handler,
		},
		{
			MethodName: "GetUserByEmail",
			Handler:    _UserAuthService_GetUserByEmail_Handler,
		},
		{
			MethodName: "ResolveCredential",
			Handler:    _UserAuthService_ResolveCredential_Handler,
		},
		{
			MethodName: "ListUserCredentials",
			Handler:    _UserAuthService_ListUserCredentials_Handler,
		},
		{
			MethodName: "GetCredential",
			Handler:    _UserAuthService_GetCredential_Handler,
		},
		{
			MethodName: "DeleteCredential",
			Handler:    _UserAuthService_DeleteCredential_Handler,
		},
		{
			MethodName: "MarkCredentialUsed",
			Handler:    _UserAuthService_MarkCredentialUsed_Handler,
		},
		{
			MethodName: "AdminListCredentials",
			Handler:    _UserAuthService_AdminListCredentials_Handler,
		},
		{
			MethodName: "UpdateCredentialStatus",
			Handler:    _UserAuthService_UpdateCredentialStatus_Handler,
		},
		{
			MethodName: "CreateUserCredential",
			Handler:    _UserAuthService_CreateUserCredential_Handler,
		},
		{
			MethodName: "DeleteUserCredentialForUser",
			Handler:    _UserAuthService_DeleteUserCredentialForUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/v1/auth.proto",
}
